apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: leafer-

images:
  - name: image-render-server
    newName: image-render-server
    newTag: leafer

patches:
  - target:
      kind: Service
      name: image-render-server
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 3000
      - op: replace
        path: /spec/ports/0/targetPort
        value: 3000
