x-common-args: &common-args
  BASE_IMAGE: docker.m.daocloud.io/library/node:23-slim
  DEBIAN_MIRROR: mirrors.aliyun.com

services:
  leafer:
    build:
      context: .
      dockerfile: packages/leafer-engine/Dockerfile
      args:
        <<: *common-args
    ports:
      - "3000:3000"

  fabric5:
    build:
      context: .
      dockerfile: packages/fabric5-engine/Dockerfile
      args:
        <<: *common-args
    ports:
      - "3001:3000"

  fabric:
    build:
      context: .
      dockerfile: packages/fabric-engine/Dockerfile
      args:
        <<: *common-args
    ports:
      - "3002:3000"

  playwright:
    build:
      context: .
      dockerfile: packages/playwright-engine/Dockerfile
      args:
        <<: *common-args
    ports:
      - "3003:3000"

  konva:
    build:
      context: .
      dockerfile: packages/konva-engine/Dockerfile
      args:
        <<: *common-args
    ports:
      - "3004:3000"
