apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: fabric5-

images:
  - name: image-render-server
    newName: registry/image-render-server
    newTag: fabric5
