export type { ImageFormat, RenderOptions, Quantity, CompressLevel } from "./types.js";
export { toQuantity } from "./types.js";
export type { Engine } from "./engine.js";
export type { FontDefinition, FontRegistry, ScanFontsOptions } from "./fonts.js";
export { DEFAULT_WEIGHT_MAP, scanFontsDir, resolveFontsDir, autoRegisterFonts } from "./fonts.js";
export { logger } from "./logger.js";
export { PerfTimer } from "./perf.js";
export { resolveVariables } from "./resolve-variables.js";
export type { ImageLoader, ImageDecoder, HttpImageLoaderOptions } from "./image-loader.js";
export { createHttpImageLoader, createNoopImageLoader } from "./image-loader.js";
export { createRenderWorker } from "./worker.js";
export { ObjectPool } from "./pool.js";
export type { PatchedCanvas } from "./canvas-patch.js";
export { patchCanvas } from "./canvas-patch.js";
export { encodePngRgba } from "./encode.js";
export type { ImageLike, FabricObject, FabricTemplateJson, FabricObjectLike } from "./fabric-shared.js";
export { normalizeImageOptions, collectImageUrls } from "./fabric-shared.js";
