version: '1.0'
name: CI
displayName: CI

triggers:
  push:
    branches:
      include:
        - master
  pull_request:
    branches:
      include:
        - master

pipeline:
  node:
    image: node:23
    steps:
      - checkout: {}
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
