version: '1.0'
name: CI
displayName: Gitee Go CI

triggers:
  push:
    branches:
      include:
        - master
  pull_request:
    branches:
      include:
        - master

stages:
  - name: lint
    displayName: Lint
    jobs:
      - name: lint
        displayName: Run lint
        runs-on: ubuntu-latest
        steps:
          - checkout: {}
          - run: |
              corepack enable
              corepack prepare pnpm@latest --activate
          - run: pnpm install
          - run: pnpm run lint

  - name: build
    displayName: Build
    jobs:
      - name: build
        displayName: Run build
        runs-on: ubuntu-latest
        steps:
          - checkout: {}
          - run: |
              corepack enable
              corepack prepare pnpm@latest --activate
          - run: pnpm install
          - run: pnpm run build

  - name: test
    displayName: Test
    jobs:
      - name: test
        displayName: Run tests
        runs-on: ubuntu-latest
        steps:
          - checkout: {}
          - run: |
              corepack enable
              corepack prepare pnpm@latest --activate
          - run: pnpm install
          - run: pnpm run build
          - run: pnpm run test
